---

language: ruby
cache: bundler
sudo: false

before_install: ./travis/before_install
install: make
script: bundle exec rspec
bundler_args: --without=development

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

rvm:
  - 2.6.6

matrix:
  include:
    - env: VAGRANT_VERSION=v2.2.9
    - env: VAGRANT_VERSION=v2.2.8
    - env: VAGRANT_VERSION=v2.2.7
    - env: VAGRANT_VERSION=v2.2.6
    - env: VAGRANT_VERSION=v2.2.5
    - env: VAGRANT_VERSION=v2.2.4
    - env: VAGRANT_VERSION=master
  allow_failures:
    - env: VAGRANT_VERSION=master
